/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    MultiEscrow: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "function",
          name: "createEscrow",
          inputs: [
            {
              name: "_payee",
              type: "address",
              internalType: "address",
            },
            {
              name: "_arbiter",
              type: "address",
              internalType: "address",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "escrowCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "escrows",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "payer",
              type: "address",
              internalType: "address",
            },
            {
              name: "payee",
              type: "address",
              internalType: "address",
            },
            {
              name: "arbiter",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentState",
              type: "uint8",
              internalType: "enum State",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "refund",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "releaseFunds",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "FundDeposited",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "payer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FundRefunded",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "payer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FundReleased",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "payee",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "IncorrectDepositAmount",
          inputs: [
            {
              name: "expected",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "actual",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidState",
          inputs: [
            {
              name: "expected",
              type: "uint8",
              internalType: "enum State",
            },
            {
              name: "current",
              type: "uint8",
              internalType: "enum State",
            },
          ],
        },
      ],
      inheritedFunctions: {},
    },
  },
  11155111: {
    MultiEscrow: {
      address: "0x70121565c51f5bd11a2f5fc2797df883f22d7963",
      abi: [
        {
          type: "function",
          name: "createEscrow",
          inputs: [
            {
              name: "_payee",
              type: "address",
              internalType: "address",
            },
            {
              name: "_arbiter",
              type: "address",
              internalType: "address",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deposit",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "escrowCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "escrows",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "payer",
              type: "address",
              internalType: "address",
            },
            {
              name: "payee",
              type: "address",
              internalType: "address",
            },
            {
              name: "arbiter",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currentState",
              type: "uint8",
              internalType: "enum State",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "refund",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "releaseFunds",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "FundDeposited",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "payer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FundRefunded",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "payer",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "FundReleased",
          inputs: [
            {
              name: "escrowId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "payee",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "IncorrectDepositAmount",
          inputs: [
            {
              name: "expected",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "actual",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidState",
          inputs: [
            {
              name: "expected",
              type: "uint8",
              internalType: "enum State",
            },
            {
              name: "current",
              type: "uint8",
              internalType: "enum State",
            },
          ],
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
